# Замените devcraft.xliff на имя вашего плагина, например: my-plugin.xliff
files:
  - source: /upload/devcraft/locales/ru_RU/devcraft.xliff
    translation: /upload/devcraft/locales/%locale_with_underscore%/%file_name%.%file_extension%
